### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by rahulrrixe**
@abompard I have added this for basic automatic build reporting.

### CODE REVIEW

**Comment by rahulrrixe** [comment]
@abompard my other commits also got added up to this requests.

**Comment by rahulrrixe** [comment]
@abompard  done :+1:

**Comment by pypingou** [comment]
I was seeing this pull-request after seeing: https://github.com/fedora-infra/fresque/pull/2/files#diff-04c6e90faac2675aa89e2176d2eec7d8R66

Does it make much sense then?

**Comment by rahulrrixe** [comment]
@pypingou this pull request is different. I have .travis.yml file for build process reporting.

**Comment by ralphbean** [comment]
This looks fine and simple to me.

**Comment by rahulrrixe** [comment]
Is their any change I need to make on this?

**Comment by pypingou** [comment]
I was just wondering, since fresque depends on pygit2 which itself depends on libgit2 which is a pure C(++) library which cannot be installed by pip, will travis work? Even to just check if it compiles, I would expect it will need all the dependencies installed so would it work?

**Comment by bochecha** [comment]
> which cannot be installed by pip

It can still be [installed inside a virtualenv](http://www.pygit2.org/install.html#libgit2-within-a-virtual-environment), so you can do that in Travis.

**Comment by rahulrrixe** [comment]
@pypingou updated to support libgit2.

**Comment by pypingou** [comment]
@rahulrrixe seems to be missing the piece about ``LIBGIT2``

**Comment by rahulrrixe** [comment]
@pypingou couldn't got your last comment :(.

**Comment by pypingou** [comment]
See the link from bochecha

**Comment by ralphbean** [comment]
@pypingou he's just doing it a different way.  It looks fine to me.

**Comment by pypingou** [comment]
@ralphbean ah, I think I see now with the env variable iiuc

**Comment by ralphbean** [comment]
OK - I'm merging this and turning on the travis webhook.  Thanks so much @rahulrrixe!

**Pull request merged**
